window.TRACKING_DATA = {
  "generated_at": "2026-07-18 15:55:19",
  "today": {
    "date": "2026-07-18",
    "weekday": "周六",
    "week": 5,
    "rhythm": "半天深度块 / 陪伴",
    "main_task": "",
    "exercise": "",
    "ai_push": "",
    "relation": "",
    "output": ""
  },
  "week": {
    "num": 5,
    "exercise": 0,
    "ai": 0,
    "relation": 0,
    "exercise_target": 5,
    "ai_target": 3,
    "relation_target": 1,
    "days": [
      {
        "date": "2026-07-15",
        "weekday": "周三",
        "week": 5,
        "rhythm": "关系优先夜",
        "main_task": "",
        "exercise": "",
        "ai_push": "",
        "output": "",
        "relation": "",
        "wrapup": "",
        "three_tasks": "",
        "notes": ""
      },
      {
        "date": "2026-07-16",
        "weekday": "周四",
        "week": 5,
        "rhythm": "AI/赚钱项目继续推进",
        "main_task": "",
        "exercise": "",
        "ai_push": "",
        "output": "",
        "relation": "",
        "wrapup": "",
        "three_tasks": "",
        "notes": ""
      },
      {
        "date": "2026-07-17",
        "weekday": "周五",
        "week": 5,
        "rhythm": "轻复盘 + 放松",
        "main_task": "",
        "exercise": "",
        "ai_push": "",
        "output": "",
        "relation": "",
        "wrapup": "",
        "three_tasks": "",
        "notes": ""
      },
      {
        "date": "2026-07-18",
        "weekday": "周六",
        "week": 5,
        "rhythm": "半天深度块 / 陪伴",
        "main_task": "",
        "exercise": "",
        "ai_push": "",
        "output": "",
        "relation": "",
        "wrapup": "",
        "three_tasks": "",
        "notes": ""
      },
      {
        "date": "2026-07-19",
        "weekday": "周日",
        "week": 5,
        "rhythm": "周复盘 + 陪伴",
        "main_task": "",
        "exercise": "",
        "ai_push": "",
        "output": "",
        "relation": "",
        "wrapup": "",
        "three_tasks": "",
        "notes": ""
      },
      {
        "date": "2026-07-20",
        "weekday": "周一",
        "week": 5,
        "rhythm": "主业复盘 + AI学习",
        "main_task": "",
        "exercise": "",
        "ai_push": "",
        "output": "",
        "relation": "",
        "wrapup": "",
        "three_tasks": "",
        "notes": ""
      },
      {
        "date": "2026-07-21",
        "weekday": "周二",
        "week": 5,
        "rhythm": "AI/赚钱项目推进",
        "main_task": "",
        "exercise": "",
        "ai_push": "",
        "output": "",
        "relation": "",
        "wrapup": "",
        "three_tasks": "",
        "notes": ""
      }
    ]
  },
  "streak": {
    "exercise_days": 0
  },
  "tip": {},
  "work_items": [
    {
      "level": "核心",
      "name": "CX1项目获取",
      "clients": "吉利 / 大众 / 长安",
      "goal": "推进CX1项目机会获取，形成客户侧持续推进节奏",
      "phase": "项目获取"
    },
    {
      "level": "核心",
      "name": "8397下一代产品定义",
      "clients": "8387 / Gen5.5产品",
      "goal": "收敛下一代产品定义，明确产品边界、核心卖点和落地路径",
      "phase": "产品定义"
    },
    {
      "level": "核心",
      "name": "AI座舱内部迭代",
      "clients": "MRD通过 / PRD通过 / 项目启动",
      "goal": "推动AI座舱从需求定义进入正式项目启动",
      "phase": "内部迭代"
    },
    {
      "level": "核心",
      "name": "AI座舱全栈项目获取",
      "clients": "广本",
      "goal": "获取广本AI座舱全栈项目机会",
      "phase": "项目获取"
    },
    {
      "level": "其他重点",
      "name": "出海项目推进",
      "clients": "赛力斯 / 斑马 / 合规 / 报价",
      "goal": "把出海项目关键议题推进到可决策、可报价、可落地状态",
      "phase": "出海项目"
    },
    {
      "level": "其他重点",
      "name": "EMS业务推进",
      "clients": "四维",
      "goal": "推进EMS业务与四维形成明确合作或项目路径",
      "phase": "业务获取"
    },
    {
      "level": "其他重点",
      "name": "ADAS话题推进",
      "clients": "8650方案 / 中国 / 德国",
      "goal": "形成8650 ADAS方案并完成中国、德国关键汇报",
      "phase": "方案汇报"
    },
    {
      "level": "其他重点",
      "name": "机器人业务方向",
      "clients": "机器人业务",
      "goal": "明确机器人业务的思路、方向和下一步探索路径",
      "phase": "方向定义"
    },
    {
      "level": "其他重点",
      "name": "出海用户研究",
      "clients": "海外用户 / 出海市场",
      "goal": "加深对出海用户、场景、需求差异和体验预期的理解",
      "phase": "用户研究"
    },
    {
      "level": "其他重点",
      "name": "团队战斗力提升",
      "clients": "团队 / 组织能力",
      "goal": "形成提升团队战斗力的系统思考和可落地动作",
      "phase": "组织能力"
    }
  ],
  "overview": {
    "平衡型时间安排：12 周执行总览": "",
    "开始日期": "2026-06-17",
    "当前周": "",
    "运动完成天数": "",
    "AI/赚钱推进次数": "",
    "高质量陪伴次数": "",
    "达标周数": "",
    "执行提醒": "每天最多三类任务"
  },
  "daily": [
    {
      "date": "2026-06-17",
      "weekday": "周三",
      "week": 1,
      "rhythm": "关系优先夜",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-06-18",
      "weekday": "周四",
      "week": 1,
      "rhythm": "AI/赚钱项目继续推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-06-19",
      "weekday": "周五",
      "week": 1,
      "rhythm": "轻复盘 + 放松",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-06-20",
      "weekday": "周六",
      "week": 1,
      "rhythm": "半天深度块 / 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-06-21",
      "weekday": "周日",
      "week": 1,
      "rhythm": "周复盘 + 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-06-22",
      "weekday": "周一",
      "week": 1,
      "rhythm": "主业复盘 + AI学习",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-06-23",
      "weekday": "周二",
      "week": 1,
      "rhythm": "AI/赚钱项目推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-06-24",
      "weekday": "周三",
      "week": 2,
      "rhythm": "关系优先夜",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-06-25",
      "weekday": "周四",
      "week": 2,
      "rhythm": "AI/赚钱项目继续推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-06-26",
      "weekday": "周五",
      "week": 2,
      "rhythm": "轻复盘 + 放松",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-06-27",
      "weekday": "周六",
      "week": 2,
      "rhythm": "半天深度块 / 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-06-28",
      "weekday": "周日",
      "week": 2,
      "rhythm": "周复盘 + 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-06-29",
      "weekday": "周一",
      "week": 2,
      "rhythm": "主业复盘 + AI学习",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-06-30",
      "weekday": "周二",
      "week": 2,
      "rhythm": "AI/赚钱项目推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-01",
      "weekday": "周三",
      "week": 3,
      "rhythm": "关系优先夜",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-02",
      "weekday": "周四",
      "week": 3,
      "rhythm": "AI/赚钱项目继续推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-03",
      "weekday": "周五",
      "week": 3,
      "rhythm": "轻复盘 + 放松",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-04",
      "weekday": "周六",
      "week": 3,
      "rhythm": "半天深度块 / 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-05",
      "weekday": "周日",
      "week": 3,
      "rhythm": "周复盘 + 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-06",
      "weekday": "周一",
      "week": 3,
      "rhythm": "主业复盘 + AI学习",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-07",
      "weekday": "周二",
      "week": 3,
      "rhythm": "AI/赚钱项目推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-08",
      "weekday": "周三",
      "week": 4,
      "rhythm": "关系优先夜",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-09",
      "weekday": "周四",
      "week": 4,
      "rhythm": "AI/赚钱项目继续推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-10",
      "weekday": "周五",
      "week": 4,
      "rhythm": "轻复盘 + 放松",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-11",
      "weekday": "周六",
      "week": 4,
      "rhythm": "半天深度块 / 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-12",
      "weekday": "周日",
      "week": 4,
      "rhythm": "周复盘 + 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-13",
      "weekday": "周一",
      "week": 4,
      "rhythm": "主业复盘 + AI学习",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-14",
      "weekday": "周二",
      "week": 4,
      "rhythm": "AI/赚钱项目推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-15",
      "weekday": "周三",
      "week": 5,
      "rhythm": "关系优先夜",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-16",
      "weekday": "周四",
      "week": 5,
      "rhythm": "AI/赚钱项目继续推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-17",
      "weekday": "周五",
      "week": 5,
      "rhythm": "轻复盘 + 放松",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-18",
      "weekday": "周六",
      "week": 5,
      "rhythm": "半天深度块 / 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-19",
      "weekday": "周日",
      "week": 5,
      "rhythm": "周复盘 + 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-20",
      "weekday": "周一",
      "week": 5,
      "rhythm": "主业复盘 + AI学习",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-21",
      "weekday": "周二",
      "week": 5,
      "rhythm": "AI/赚钱项目推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-22",
      "weekday": "周三",
      "week": 6,
      "rhythm": "关系优先夜",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-23",
      "weekday": "周四",
      "week": 6,
      "rhythm": "AI/赚钱项目继续推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-24",
      "weekday": "周五",
      "week": 6,
      "rhythm": "轻复盘 + 放松",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-25",
      "weekday": "周六",
      "week": 6,
      "rhythm": "半天深度块 / 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-26",
      "weekday": "周日",
      "week": 6,
      "rhythm": "周复盘 + 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-27",
      "weekday": "周一",
      "week": 6,
      "rhythm": "主业复盘 + AI学习",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-28",
      "weekday": "周二",
      "week": 6,
      "rhythm": "AI/赚钱项目推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-29",
      "weekday": "周三",
      "week": 7,
      "rhythm": "关系优先夜",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-30",
      "weekday": "周四",
      "week": 7,
      "rhythm": "AI/赚钱项目继续推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-07-31",
      "weekday": "周五",
      "week": 7,
      "rhythm": "轻复盘 + 放松",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-01",
      "weekday": "周六",
      "week": 7,
      "rhythm": "半天深度块 / 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-02",
      "weekday": "周日",
      "week": 7,
      "rhythm": "周复盘 + 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-03",
      "weekday": "周一",
      "week": 7,
      "rhythm": "主业复盘 + AI学习",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-04",
      "weekday": "周二",
      "week": 7,
      "rhythm": "AI/赚钱项目推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-05",
      "weekday": "周三",
      "week": 8,
      "rhythm": "关系优先夜",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-06",
      "weekday": "周四",
      "week": 8,
      "rhythm": "AI/赚钱项目继续推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-07",
      "weekday": "周五",
      "week": 8,
      "rhythm": "轻复盘 + 放松",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-08",
      "weekday": "周六",
      "week": 8,
      "rhythm": "半天深度块 / 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-09",
      "weekday": "周日",
      "week": 8,
      "rhythm": "周复盘 + 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-10",
      "weekday": "周一",
      "week": 8,
      "rhythm": "主业复盘 + AI学习",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-11",
      "weekday": "周二",
      "week": 8,
      "rhythm": "AI/赚钱项目推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-12",
      "weekday": "周三",
      "week": 9,
      "rhythm": "关系优先夜",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-13",
      "weekday": "周四",
      "week": 9,
      "rhythm": "AI/赚钱项目继续推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-14",
      "weekday": "周五",
      "week": 9,
      "rhythm": "轻复盘 + 放松",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-15",
      "weekday": "周六",
      "week": 9,
      "rhythm": "半天深度块 / 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-16",
      "weekday": "周日",
      "week": 9,
      "rhythm": "周复盘 + 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-17",
      "weekday": "周一",
      "week": 9,
      "rhythm": "主业复盘 + AI学习",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-18",
      "weekday": "周二",
      "week": 9,
      "rhythm": "AI/赚钱项目推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-19",
      "weekday": "周三",
      "week": 10,
      "rhythm": "关系优先夜",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-20",
      "weekday": "周四",
      "week": 10,
      "rhythm": "AI/赚钱项目继续推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-21",
      "weekday": "周五",
      "week": 10,
      "rhythm": "轻复盘 + 放松",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-22",
      "weekday": "周六",
      "week": 10,
      "rhythm": "半天深度块 / 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-23",
      "weekday": "周日",
      "week": 10,
      "rhythm": "周复盘 + 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-24",
      "weekday": "周一",
      "week": 10,
      "rhythm": "主业复盘 + AI学习",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-25",
      "weekday": "周二",
      "week": 10,
      "rhythm": "AI/赚钱项目推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-26",
      "weekday": "周三",
      "week": 11,
      "rhythm": "关系优先夜",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-27",
      "weekday": "周四",
      "week": 11,
      "rhythm": "AI/赚钱项目继续推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-28",
      "weekday": "周五",
      "week": 11,
      "rhythm": "轻复盘 + 放松",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-29",
      "weekday": "周六",
      "week": 11,
      "rhythm": "半天深度块 / 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-30",
      "weekday": "周日",
      "week": 11,
      "rhythm": "周复盘 + 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-08-31",
      "weekday": "周一",
      "week": 11,
      "rhythm": "主业复盘 + AI学习",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-09-01",
      "weekday": "周二",
      "week": 11,
      "rhythm": "AI/赚钱项目推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-09-02",
      "weekday": "周三",
      "week": 12,
      "rhythm": "关系优先夜",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-09-03",
      "weekday": "周四",
      "week": 12,
      "rhythm": "AI/赚钱项目继续推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-09-04",
      "weekday": "周五",
      "week": 12,
      "rhythm": "轻复盘 + 放松",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-09-05",
      "weekday": "周六",
      "week": 12,
      "rhythm": "半天深度块 / 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-09-06",
      "weekday": "周日",
      "week": 12,
      "rhythm": "周复盘 + 陪伴",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-09-07",
      "weekday": "周一",
      "week": 12,
      "rhythm": "主业复盘 + AI学习",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    },
    {
      "date": "2026-09-08",
      "weekday": "周二",
      "week": 12,
      "rhythm": "AI/赚钱项目推进",
      "main_task": "",
      "exercise": "",
      "ai_push": "",
      "output": "",
      "relation": "",
      "wrapup": "",
      "three_tasks": "",
      "notes": ""
    }
  ],
  "weekly": [
    {
      "week": "W1",
      "date_range": "2026-06-17 至 2026-06-23",
      "main_achievement": "",
      "ai_deliverable": "",
      "exercise_days": 0,
      "ai_count": 0,
      "relation_count": 0,
      "judgment": "",
      "passed": "未达标",
      "next_tweak": ""
    },
    {
      "week": "W2",
      "date_range": "2026-06-24 至 2026-06-30",
      "main_achievement": "",
      "ai_deliverable": "",
      "exercise_days": 0,
      "ai_count": 0,
      "relation_count": 0,
      "judgment": "",
      "passed": "未达标",
      "next_tweak": ""
    },
    {
      "week": "W3",
      "date_range": "2026-07-01 至 2026-07-07",
      "main_achievement": "",
      "ai_deliverable": "",
      "exercise_days": 0,
      "ai_count": 0,
      "relation_count": 0,
      "judgment": "",
      "passed": "",
      "next_tweak": ""
    },
    {
      "week": "W4",
      "date_range": "2026-07-08 至 2026-07-14",
      "main_achievement": "",
      "ai_deliverable": "",
      "exercise_days": 0,
      "ai_count": 0,
      "relation_count": 0,
      "judgment": "",
      "passed": "未达标",
      "next_tweak": ""
    },
    {
      "week": "W5",
      "date_range": "2026-07-15 至 2026-07-21",
      "main_achievement": "",
      "ai_deliverable": "",
      "exercise_days": 0,
      "ai_count": 0,
      "relation_count": 0,
      "judgment": "",
      "passed": "",
      "next_tweak": ""
    },
    {
      "week": "W6",
      "date_range": "2026-07-22 至 2026-07-28",
      "main_achievement": "",
      "ai_deliverable": "",
      "exercise_days": 0,
      "ai_count": 0,
      "relation_count": 0,
      "judgment": "",
      "passed": "",
      "next_tweak": ""
    },
    {
      "week": "W7",
      "date_range": "2026-07-29 至 2026-08-04",
      "main_achievement": "",
      "ai_deliverable": "",
      "exercise_days": 0,
      "ai_count": 0,
      "relation_count": 0,
      "judgment": "",
      "passed": "",
      "next_tweak": ""
    },
    {
      "week": "W8",
      "date_range": "2026-08-05 至 2026-08-11",
      "main_achievement": "",
      "ai_deliverable": "",
      "exercise_days": 0,
      "ai_count": 0,
      "relation_count": 0,
      "judgment": "",
      "passed": "",
      "next_tweak": ""
    },
    {
      "week": "W9",
      "date_range": "2026-08-12 至 2026-08-18",
      "main_achievement": "",
      "ai_deliverable": "",
      "exercise_days": 0,
      "ai_count": 0,
      "relation_count": 0,
      "judgment": "",
      "passed": "",
      "next_tweak": ""
    },
    {
      "week": "W10",
      "date_range": "2026-08-19 至 2026-08-25",
      "main_achievement": "",
      "ai_deliverable": "",
      "exercise_days": 0,
      "ai_count": 0,
      "relation_count": 0,
      "judgment": "",
      "passed": "",
      "next_tweak": ""
    },
    {
      "week": "W11",
      "date_range": "2026-08-26 至 2026-09-01",
      "main_achievement": "",
      "ai_deliverable": "",
      "exercise_days": 0,
      "ai_count": 0,
      "relation_count": 0,
      "judgment": "",
      "passed": "",
      "next_tweak": ""
    },
    {
      "week": "W12",
      "date_range": "2026-09-02 至 2026-09-08",
      "main_achievement": "",
      "ai_deliverable": "",
      "exercise_days": 0,
      "ai_count": 0,
      "relation_count": 0,
      "judgment": "",
      "passed": "",
      "next_tweak": ""
    }
  ],
  "plan": {
    "start": "2026-06-17",
    "end": "2026-09-08",
    "total_days": 84,
    "days_elapsed": 31
  }
};